---
- name: install nginx
  hosts: webservers
  tasks:
    - name: nginx installation
      apt:
        name: nginx
        state: present
        update_cache: yes
    - name: create index.html
      copy:
        dest: /var/www/html/index.html
        content: "welcome to Nginx via playbook ip 65 to ip 66"
    - name: start nginx
      service:
        name: nginx
        state: started
        enabled: yes
    - name: allow firewall
      ufw: 
        rule: allow
        port: '80'
        proto: tcp
        state: enabled