---
- name: user creation playbook
  hosts: webservers
  tasks:
    - name: adding user
      user:
        name: a1
        comment: a1
        uid: 1090
        group: sudo
- name: multifile creation in allservers playbook
  hosts: webservers
  tasks:
    - name: multiple file creation using list
      file:
        path: "/tmp/{{item}}"
        state: touch
      with_items:
        - t1.txt
        - t2.txt
        - t3.txt
...